version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/bots.db
    restart: unless-stopped 